# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headlineScraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('one_line', models.TextField(max_length=200)),
                ('ip', models.GenericIPAddressField()),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('key', models.CharField(choices=[('IGNORE', 'Ignore'), ('HIGH', 'High'), ('MID', 'Mid'), ('LOW', 'Low')], default='IGNORE', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reports', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.Report')),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submission.ReportCategory'),
        ),
        migrations.AddField(
            model_name='report',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline'),
        ),
    ]
