# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_auto_20171128_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinesummary',
            name='one_line',
            field=models.TextField(max_length=2000),
        ),
    ]
