# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_auto_20171130_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='explanation',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
