# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleScraper', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.NewsSite'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='photographers',
            field=models.ManyToManyField(to='articleScraper.Photographer'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.NewsSite'),
        ),
    ]
