# Generated by Django 2.1.4 on 2019-07-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleScraper', '0001_initial'),
        ('newsSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalist',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsSite.NewsSite'),
        ),
        migrations.AddField(
            model_name='diff',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Revision'),
        ),
        migrations.AddField(
            model_name='content',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Revision'),
        ),
        migrations.AddField(
            model_name='child',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Content'),
        ),
        migrations.AddField(
            model_name='change',
            name='diff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Diff'),
        ),
        migrations.AddField(
            model_name='articleurltemplate',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsSite.NewsSite'),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='photographers',
            field=models.ManyToManyField(to='articleScraper.Photographer'),
        ),
        migrations.AddField(
            model_name='article',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsSite.NewsSite', verbose_name='news site name'),
        ),
    ]
