# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0002_auto_20171128_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletemplate',
            name='datetime_attribute',
            field=models.CharField(default='datetime', max_length=255),
        ),
    ]
