# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0003_articletemplate_datetime_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='/home/sindre/Documents/NewsEnhancer/sites'),
        ),
    ]
