# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0004_auto_20180105_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletemplate',
            name='timezone',
            field=models.CharField(default='Europe/Oslo', max_length=255),
        ),
    ]
