# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0005_articletemplate_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='datetime_attribute',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
