# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0008_articletemplate_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletemplate',
            name='selector',
            field=models.CharField(default='article', max_length=255),
        ),
    ]
