# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-10 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0009_auto_20180203_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='D:\\Git\\Bitbucket\\master\\newsenhancer\\sites'),
        ),
    ]
