# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0012_auto_20180219_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleurltemplate',
            name='id_separator',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
