# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0015_auto_20180305_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='/home/sindre/Documents/NewsEnhancer/resources/sites'),
        ),
    ]
