# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0016_auto_20180307_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleurltemplate',
            name='id_type',
            field=models.CharField(choices=[('ALPHA_NUMERIC', 'AlphaNumeric'), ('NUMBERS_ONLY', 'Numbers only'), ('LETTERS_ONLY', 'Letters only'), ('OTHER', 'Other')], default='OTHER', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='/Users/sindre/Developer/Git/Bitbucket/master/newsenhancer/resources/articles'),
        ),
    ]
