# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-09-24 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0017_auto_20180308_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='/webapps/newsenhancer/articles'),
        ),
    ]
