# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-23 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0018_auto_20180924_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='file',
            field=models.FilePathField(blank=True, path='/home/steffen/dev/master/baitBlock-server/articles'),
        ),
    ]
