# Generated by Django 2.1.4 on 2019-03-19 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0019_auto_20190123_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('tag', models.TextField(default=None, null=True)),
                ('content', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='revision',
            name='file',
        ),
        migrations.AddField(
            model_name='content',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Revision'),
        ),
    ]
