# Generated by Django 2.1.4 on 2019-03-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0020_auto_20190319_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='nrChildren',
            field=models.IntegerField(default=0),
        ),
    ]
