# Generated by Django 2.1.4 on 2019-03-19 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0021_content_nrchildren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='nrChildren',
        ),
        migrations.AlterField(
            model_name='content',
            name='pos',
            field=models.IntegerField(default=-1),
        ),
    ]
