# Generated by Django 2.1.4 on 2019-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0023_auto_20190320_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='child',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='content',
            name='pos',
            field=models.IntegerField(default=-1),
        ),
    ]
