# Generated by Django 2.1.4 on 2019-03-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0024_auto_20190320_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article',
            field=models.TextField(default=None, null=True),
        ),
    ]
