# Generated by Django 2.1.4 on 2019-04-01 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0026_auto_20190322_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
    ]
