# Generated by Django 2.1.4 on 2019-04-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0027_remove_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='content',
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('pos',)},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('-version',)},
        ),
        migrations.RemoveField(
            model_name='article',
            name='article',
        ),
        migrations.DeleteModel(
            name='Child',
        ),
    ]
