# Generated by Django 2.1.4 on 2019-06-05 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0029_diff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diff',
            name='article',
        ),
        migrations.DeleteModel(
            name='Diff',
        ),
    ]
