# Generated by Django 2.1.4 on 2019-06-05 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0030_auto_20190605_0755'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diff', models.TextField(default=None, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Article')),
            ],
        ),
    ]
