# Generated by Django 2.1.4 on 2019-07-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0031_diff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diff',
            options={'ordering': ['article']},
        ),
    ]
