# Generated by Django 2.1.4 on 2019-07-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0032_auto_20190709_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diff',
            options={'ordering': ('article',)},
        ),
    ]
