# Generated by Django 2.1.4 on 2019-07-12 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0033_auto_20190709_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, null=True)),
                ('type_of_change', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.IntegerField(default=-1)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Content')),
            ],
            options={
                'ordering': ('content',),
            },
        ),
        migrations.RenameField(
            model_name='diff',
            old_name='diff',
            new_name='new_content',
        ),
        migrations.AddField(
            model_name='diff',
            name='old_content',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='change',
            name='diff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Diff'),
        ),
    ]
