# Generated by Django 2.1.4 on 2019-07-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0034_auto_20190712_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ('pos',)},
        ),
        migrations.AddField(
            model_name='change',
            name='pos',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
