# Generated by Django 2.1.4 on 2019-07-13 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0035_auto_20190713_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['modified']},
        ),
        migrations.AlterModelOptions(
            name='diff',
            options={'ordering': ('id',)},
        ),
        migrations.RemoveField(
            model_name='diff',
            name='article',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='new_content',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='old_content',
        ),
        migrations.AddField(
            model_name='diff',
            name='revision',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articleScraper.Revision'),
            preserve_default=False,
        ),
    ]
