# Generated by Django 2.1.4 on 2019-07-15 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0036_auto_20190713_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-headline',)},
        ),
        migrations.AlterModelOptions(
            name='revision',
            options={'ordering': ('version',)},
        ),
        migrations.RemoveField(
            model_name='articletemplate',
            name='selector',
        ),
        migrations.AddField(
            model_name='articletemplate',
            name='search_for',
            field=models.CharField(default='p', max_length=255),
        ),
    ]
