# Generated by Django 2.1.4 on 2019-07-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0037_auto_20190715_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletemplate',
            name='video',
        ),
    ]
