# Generated by Django 2.1.4 on 2019-07-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleScraper', '0038_remove_articletemplate_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created',
        ),
        migrations.RemoveField(
            model_name='article',
            name='modified',
        ),
    ]
