# Generated by Django 2.1.4 on 2019-07-26 17:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, null=True)),
                ('type_of_change', models.IntegerField(default=None, null=True)),
                ('pos', models.IntegerField(default=None, null=True)),
                ('title', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('pos',),
            },
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(null=True, verbose_name='time Of Edit')),
                ('category', models.CharField(choices=[('ARTICLE', 'Article'), ('FEED', 'Feed'), ('EXTERNAL', 'External'), ('VIDEO', 'Video')], default='ARTICLE', max_length=255)),
                ('url_id', models.CharField(default='', max_length=255)),
                ('url', models.URLField(max_length=2500, unique=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HeadlineRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(null=True, verbose_name='time of revision')),
                ('version', models.IntegerField(verbose_name='version number')),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline')),
            ],
            options={
                'ordering': ('version',),
            },
        ),
        migrations.CreateModel(
            name='HeadlineTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('headline', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('sub_title', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('exclude', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None)),
                ('list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('feed', models.CharField(default=None, max_length=255, null=True)),
                ('video', models.CharField(default='/video/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('placement', models.IntegerField()),
                ('of_total', models.IntegerField()),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='headlineScraper.Headline')),
            ],
        ),
    ]
