# Generated by Django 2.1.4 on 2019-07-26 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('headlineScraper', '0001_initial'),
        ('newsSite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='news_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsSite.NewsSite', verbose_name='news site name'),
        ),
        migrations.AddField(
            model_name='diff',
            name='headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline'),
        ),
        migrations.AddField(
            model_name='change',
            name='diff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Diff'),
        ),
    ]
