# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0002_auto_20171128_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headline',
            name='summary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary', to='submission.HeadlineSummary'),
        ),
    ]
