# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0003_auto_20171130_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='headline',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='title',
        ),
    ]
