# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0004_auto_20171207_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadlineRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('sub_title', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline')),
            ],
        ),
    ]
