# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0005_headlinerevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='headline',
            name='url_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
