# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-07 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0007_auto_20180307_1428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['-modified']},
        ),
        migrations.AddField(
            model_name='headline',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='headlinerevision',
            name='file',
            field=models.FilePathField(blank=True, path='/home/sindre/Documents/NewsEnhancer/resources/sites'),
        ),
    ]
