# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-08 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0008_auto_20180307_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinerevision',
            name='file',
            field=models.FilePathField(blank=True, path='/Users/sindre/Developer/Git/Bitbucket/master/newsenhancer/resources/articles'),
        ),
    ]
