# Generated by Django 2.1.4 on 2019-03-11 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0011_auto_20190123_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headlinerevision',
            name='file',
        ),
    ]
