# Generated by Django 2.1.4 on 2019-04-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0012_remove_headlinerevision_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='summary',
        ),
        migrations.AddField(
            model_name='headline',
            name='category',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('FEED', 'Feed'), ('EXTERNAL', 'External'), ('VIDEO', 'Video')], default='ARTICLE', max_length=255),
        ),
    ]
