# Generated by Django 2.1.4 on 2019-07-12 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0013_auto_20190401_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, null=True)),
                ('type_of_change', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_title', models.TextField(default=None, null=True)),
                ('new_title', models.TextField(default=None, null=True)),
                ('old_sub_title', models.TextField(default=None, null=True)),
                ('new_sub_title', models.TextField(default=None, null=True)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Headline')),
            ],
            options={
                'ordering': ('headline',),
            },
        ),
        migrations.AddField(
            model_name='change',
            name='diff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.Diff'),
        ),
    ]
