# Generated by Django 2.1.4 on 2019-07-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0014_auto_20190712_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='change',
            name='pos',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
