# Generated by Django 2.1.4 on 2019-07-13 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0016_change_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='change',
            options={'ordering': ('pos',)},
        ),
        migrations.AlterModelOptions(
            name='headlinerevision',
            options={'ordering': ['-version']},
        ),
        migrations.RemoveField(
            model_name='diff',
            name='new_sub_title',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='new_title',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='old_sub_title',
        ),
        migrations.RemoveField(
            model_name='diff',
            name='old_title',
        ),
    ]
