# Generated by Django 2.1.4 on 2019-07-13 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0017_auto_20190713_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ['modified']},
        ),
        migrations.AlterModelOptions(
            name='headlinerevision',
            options={'ordering': ['version']},
        ),
    ]
