# Generated by Django 2.1.4 on 2019-07-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0019_headlinetemplate_feed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinetemplate',
            name='feed',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
