# Generated by Django 2.1.4 on 2019-07-15 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0020_auto_20190714_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headline',
            options={'ordering': ('-id',)},
        ),
    ]
