# Generated by Django 2.1.4 on 2019-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0021_auto_20190715_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='headlinetemplate',
            name='video',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
