# Generated by Django 2.1.4 on 2019-07-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0022_headlinetemplate_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diff',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='headlinerevision',
            options={'ordering': ('version',)},
        ),
        migrations.AlterField(
            model_name='headlinetemplate',
            name='video',
            field=models.CharField(default='/video/', max_length=255, null=True),
        ),
    ]
