# Generated by Django 2.1.4 on 2019-07-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0023_auto_20190716_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headlinetemplate',
            name='video',
            field=models.CharField(default='/video/', max_length=255),
        ),
    ]
