# Generated by Django 2.1.4 on 2019-07-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('headlineScraper', '0024_auto_20190716_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headline',
            name='created',
        ),
        migrations.RemoveField(
            model_name='headline',
            name='modified',
        ),
    ]
