# Generated by Django 2.1.4 on 2019-07-26 17:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articleScraper', '0001_initial'),
        ('headlineScraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name="Newspaper's name")),
                ('abbreviation', models.CharField(max_length=255)),
                ('base_url', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('current_headline_count_on_front_page', models.IntegerField(default=0)),
                ('max_headlines_count', models.IntegerField(default=0)),
                ('urls_is_not_an_article', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, default=list, size=None)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('articleTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articleScraper.ArticleTemplate', verbose_name='article template')),
                ('headlineTemplate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headlineScraper.HeadlineTemplate', verbose_name='headline template')),
            ],
        ),
    ]
